### ISSUE TITLE
Plugin working but error on console

### ISSUE THREAD

**Issue by stkeroro** [Plx0wn/MobsReward#2]
getting this error on console when a mob is killed:
`[14:10:03] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobsReward v0.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1109) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1616) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftZombie cannot be cast to org.bukkit.entity.Player
	at fr.plx0wn.Rewards.Players.onEntityKill(Players.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-9a1f5ee]
	... 23 more`

**Comment by Plx0wn** [comment]
I think is because you're using version 1.12.2 ! I'll fix that in the next update. Thank's for reporting this error!!
If you found an other error report it ! :)
